

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div className={`relative`}>
      <div className="h-full">
        {/* Main content */}
        <div
          className={`
          text-slate-900 transition duration-300 flex flex-col 
            min-h-screen font-inter dark:text-white
          `}
        >
          <main
            className={`flex-1 flex items-center justify-center flex-col px-2.5`}
          >
            {children}
          </main>
        </div>
        {/* End Main content */}
      </div>
    </div>
  )
}